f

diff --git a/.github/workflows/allocation.yml b/.github/workflows/allocation.yml
--- a/.github/workflows/allocation.yml
+++ b/.github/workflows/allocation.yml
@@ -104,7 +104,15 @@ jobs:
         run: |
           set -x 
           erc20_processor cancel-allocation --allocation-id $ALLOCATION_ID0 --account-no 1 --use-internal
-          erc20_processor cancel-allocation --allocation-id $ALLOCATION_ID1 --account-no 1 --use-internal
+          erc20_processor cancel-allocation --allocation-id $ALLOCATION_ID1 --account-no 1 --use-internal || echo "Error expected (OK)"
+          erc20_processor cancel-allocation --allocation-id $ALLOCATION_ID1 --account-no 2 --use-internal || echo "Error expected (OK)"
+          erc20_processor run
+
+      - name: Withdraw all tokens
+        run: |
+          set -x 
+          erc20_processor withdraw --account-no 1 --all
+          erc20_processor withdraw --account-no 2 --all
           erc20_processor run
 
       - name: Transfer all left ETH tokens
