f

diff --git a/.github/workflows/deposit.yml b/.github/workflows/deposit.yml
--- a/.github/workflows/deposit.yml
+++ b/.github/workflows/deposit.yml
@@ -82,39 +82,39 @@ jobs:
       - name: Make single transfer from deposit
         run: |
           set -x 
-          erc20_processor transfer --deposit-id $DEPOSIT_ID0 --account-no 2 --amount 0.0001 --recipient $ETH_ADDRESS_4 --use-internal
+          erc20_processor transfer --deposit-id $DEPOSIT_ID0 --account-no 2 --amount 0.0001 --recipient $ETH_ADDRESS_4
           erc20_processor run
 
       - name: Make single transfer without deposit
         run: |
           set -x 
-          erc20_processor transfer --account-no 1 --amount 0.0001 --recipient $ETH_ADDRESS_4 --use-internal
+          erc20_processor transfer --account-no 1 --amount 0.0001 --recipient $ETH_ADDRESS_4
           erc20_processor run
 
       - name: Make multiple transfers from deposit
         run: |
           set -x 
-          erc20_processor transfer --deposit-id $DEPOSIT_ID1 --account-no 2 --amount 0.0001 --recipient $ETH_ADDRESS_0 --use-internal
-          erc20_processor transfer --deposit-id $DEPOSIT_ID1 --account-no 2 --amount 0.0001 --recipient $ETH_ADDRESS_3 --use-internal
-          erc20_processor transfer --deposit-id $DEPOSIT_ID1 --account-no 2 --amount 0.0001 --recipient $ETH_ADDRESS_4 --use-internal
+          erc20_processor transfer --deposit-id $DEPOSIT_ID1 --account-no 2 --amount 0.0001 --recipient $ETH_ADDRESS_0
+          erc20_processor transfer --deposit-id $DEPOSIT_ID1 --account-no 2 --amount 0.0001 --recipient $ETH_ADDRESS_3
+          erc20_processor transfer --deposit-id $DEPOSIT_ID1 --account-no 2 --amount 0.0001 --recipient $ETH_ADDRESS_4
           erc20_processor run
           erc20_processor balance
 
       - name: Make multiple transfer without deposit
         run: |
           set -x 
-          erc20_processor transfer --account-no 1 --amount 0.0001 --recipient $ETH_ADDRESS_0 --use-internal
-          erc20_processor transfer --account-no 1 --amount 0.0001 --recipient $ETH_ADDRESS_3 --use-internal
-          erc20_processor transfer --account-no 1 --amount 0.0001 --recipient $ETH_ADDRESS_4 --use-internal
+          erc20_processor transfer --account-no 1 --amount 0.0001 --recipient $ETH_ADDRESS_0
+          erc20_processor transfer --account-no 1 --amount 0.0001 --recipient $ETH_ADDRESS_3
+          erc20_processor transfer --account-no 1 --amount 0.0001 --recipient $ETH_ADDRESS_4
           erc20_processor run
           erc20_processor balance
 
       - name: Free deposit
         run: |
           set -x 
-          erc20_processor cancel-deposit --deposit-id $DEPOSIT_ID0 --account-no 1 --use-internal
-          erc20_processor cancel-deposit --deposit-id $DEPOSIT_ID1 --account-no 1 --use-internal || echo "Error expected (OK)"
-          erc20_processor cancel-deposit --deposit-id $DEPOSIT_ID1 --account-no 2 --use-internal || echo "Error expected (OK)"
+          erc20_processor cancel-deposit --deposit-id $DEPOSIT_ID0 --account-no 1
+          erc20_processor cancel-deposit --deposit-id $DEPOSIT_ID1 --account-no 1 || echo "Error expected (OK)"
+          erc20_processor cancel-deposit --deposit-id $DEPOSIT_ID1 --account-no 2 || echo "Error expected (OK)"
           erc20_processor run
 
       - name: Withdraw all tokens
